/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        primary: '#4648d4',
        primaryGlow: 'rgba(70, 72, 212, 0.4)',
        textMain: '#0b1c30',
        textMuted: '#464554',
        "secondary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#464554",
        "inverse-surface": "#213145",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#5c647a",
        "tertiary-container": "#b55d00",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#ffb783",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#dae2fd",
        "surface-tint": "#494bd6",
        "secondary-container": "#dae2fd",
        "surface-container": "#e5eeff",
        "outline-variant": "#c7c4d7",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#ffdcc5",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        "secondary": "#565e74",
        "on-primary-fixed": "#07006c",
        "primary-fixed": "#e1e0ff",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "primary-container": "#6063ee",
        "on-tertiary-container": "#fffbff",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#904900",
        "inverse-primary": "#c0c1ff",
        "on-tertiary-fixed-variant": "#703700",
        "error": "#ba1a1a",
        "outline": "#767586",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-container": "#fffbff"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "h2": ["Space Grotesk"],
        "body-md": ["Inter"],
        "button": ["Inter"],
        "h3": ["Space Grotesk"],
        "h1": ["Space Grotesk"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "h2": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "button": ["16px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-bold": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      spacing: {
        "gutter": "24px",
        "md": "24px",
        "container-max": "1280px",
        "xs": "4px",
        "base": "8px",
        "xl": "80px",
        "sm": "12px",
        "lg": "48px"
      },
      animation: {
        'grid-scroll': 'grid-scroll 20s linear infinite',
      },
      keyframes: {
        'grid-scroll': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(50px)' },
        }
      }
    },
  },
  plugins: [],
}
